# Generated by Django 4.1.3 on 2022-11-10 10:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=255)),
                ('creation_datetime', models.DateTimeField(default=datetime.datetime(2022, 11, 10, 12, 24, 29, 199137))),
                ('release_datetime', models.DateTimeField()),
                ('cost', models.IntegerField(null=True)),
                ('propriet', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(upload_to='songs/images')),
                ('audio', models.FileField(upload_to='songs/audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Song', to='albums.album')),
            ],
            options={
                'db_table': 'Song',
            },
        ),
    ]
