# Generated by Django 4.1.3 on 2022-11-01 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=255)),
                ('creation_datetime', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 12, 45, 1, 883032))),
                ('release_datetime', models.DateTimeField()),
                ('cost', models.IntegerField(null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album', to='artists.artist')),
            ],
            options={
                'db_table': 'Album',
            },
        ),
    ]
