# Generated by Django 4.1.3 on 2022-11-01 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0010_alter_album_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 19, 44, 11, 450180)),
        ),
        migrations.AlterField(
            model_name='album',
            name='propriet',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
