# Generated by Django 4.1.3 on 2022-11-03 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_creation_datetime_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 14, 52, 9, 684055)),
        ),
        migrations.AlterModelTable(
            name='song',
            table='Song',
        ),
    ]
