# Generated by Django 4.1.3 on 2022-11-03 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_alter_album_creation_datetime_alter_song_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 15, 0, 11, 154561)),
        ),
    ]
