# Generated by Django 4.1.3 on 2022-11-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='approved_albums',
        ),
    ]
