# Generated by Django 4.1.3 on 2022-11-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='User_id',
            new_name='User',
        ),
    ]
